export enum CompanyType {
  SHIPPER = 'SHIPPER',
  FWD = 'FWD',
  CFS = 'CFS',
}

export enum CompanyStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  ADMIN = 'ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  SHIPPER_ADMIN = 'SHIPPER_ADMIN',
  SHIPPER_MEMBER = 'SHIPPER_MEMBER',
  FWD_ADMIN = 'FWD_ADMIN',
  FWD_OPERATOR = 'FWD_OPERATOR',
  CFS_ADMIN = 'CFS_ADMIN',
  CFS_OPERATOR = 'CFS_OPERATOR',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum ShipmentStatus {
  DRAFT = 'DRAFT',
  PRICED = 'PRICED',
  SUBMITTED = 'SUBMITTED',
  MATCHING = 'MATCHING',
  GROUPED = 'GROUPED',
  CONFIRMED = 'CONFIRMED',
  RECEIVED_CFS = 'RECEIVED_CFS',
  SEALED = 'SEALED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum QuoteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum BookingStatus {
  CONFIRMED = 'CONFIRMED',
  RECEIVED_CFS = 'RECEIVED_CFS',
  SEALED = 'SEALED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum MatchGroupStatus {
  DRAFT = 'DRAFT',
  PROPOSED = 'PROPOSED',
  CONFIRMED = 'CONFIRMED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum PackageType {
  BOX = 'BOX',
  PALLET = 'PALLET',
  CRATE = 'CRATE',
  OTHER = 'OTHER',
}

export enum ChargeableBasis {
  VOLUME = 'VOLUME',
  WEIGHT = 'WEIGHT',
}

export enum LoadingProofType {
  INBOUND_INSPECTION = 'INBOUND_INSPECTION',
  LAYER_PACKED = 'LAYER_PACKED',
  SEAL_CLOSED = 'SEAL_CLOSED',
}


